# fly.toml app configuration file generated for song-showdown on 2023-08-28T01:42:20-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "song-showdown"
primary_region = "ewr"

[build]

[http_service]
  internal_port = 3000 
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
