# fly.toml app configuration file generated for song-showdown-server on 2023-08-28T02:13:22-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "song-showdown-server"
primary_region = "ewr"

[build]

[http_service]
  internal_port = 443 
  force_https = true 
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
